### ISSUE TITLE
Ошибка линкера при сборке примеров для unwd-range-l1-r3

### ISSUE THREAD

**Issue by Arjentix** [unwireddevices/RIOT#10]
## Description
При сборке любого примера (с переменной BOARD установленной в unwd-range-l1-r3 внутри Makefile'а) происходит следующее:
```bash
arjentix@Slayer:~/Git_downloads/RIOT/examples/hello-world$ make clean && make
Building application "hello-world" for "unwd-range-l1-r3" with MCU "stm32l1".

"make" -C /home/arjentix/Git_downloads/RIOT/boards/unwd-range-l1-r3
"make" -C /home/arjentix/Git_downloads/RIOT/boards/common/unwd
"make" -C /home/arjentix/Git_downloads/RIOT/core
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/stm32l1
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/cortexm_common
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/cortexm_common/periph
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/stm32_common
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/stm32_common/periph
"make" -C /home/arjentix/Git_downloads/RIOT/cpu/stm32l1/periph
"make" -C /home/arjentix/Git_downloads/RIOT/drivers
"make" -C /home/arjentix/Git_downloads/RIOT/drivers/periph_common
"make" -C /home/arjentix/Git_downloads/RIOT/sys
"make" -C /home/arjentix/Git_downloads/RIOT/sys/auto_init
"make" -C /home/arjentix/Git_downloads/RIOT/sys/isrpipe
"make" -C /home/arjentix/Git_downloads/RIOT/sys/newlib_syscalls_default
"make" -C /home/arjentix/Git_downloads/RIOT/sys/pm_layered
"make" -C /home/arjentix/Git_downloads/RIOT/sys/stdio_uart
"make" -C /home/arjentix/Git_downloads/RIOT/sys/tsrb
/home/arjentix/Git_downloads/RIOT/examples/hello-world/bin/unwd-range-l1-r3/stm32_common.a(cpu_init.o): In function `cpu_init':
/home/arjentix/Git_downloads/RIOT/cpu/stm32_common/cpu_init.c:143: undefined reference to `cpu_init_status'
/home/arjentix/Git_downloads/RIOT/examples/hello-world/bin/unwd-range-l1-r3/stm32_common.a(stmclk_l0l1.o): In function `stmclk_init_sysclk':
/home/arjentix/Git_downloads/RIOT/cpu/stm32_common/stmclk_l0l1.c:154: undefined reference to `cpu_status'
/home/arjentix/Git_downloads/RIOT/examples/hello-world/bin/unwd-range-l1-r3/stm32_common.a(cpu_common.o): In function `periph_apb_clk':
/home/arjentix/Git_downloads/RIOT/cpu/stm32_common/cpu_common.c:105: undefined reference to `cpu_status'
collect2: error: ld returned 1 exit status
/home/arjentix/Git_downloads/RIOT/examples/hello-world/../../Makefile.include:454: recipe for target '/home/arjentix/Git_downloads/RIOT/examples/hello-world/bin/unwd-range-l1-r3/hello-world.elf' failed
make: *** [/home/arjentix/Git_downloads/RIOT/examples/hello-world/bin/unwd-range-l1-r3/hello-world.elf] Error 1
```

Operating System Environment
-----------------------------
       Operating System: "elementary OS" "5.0 Juno"
                 Kernel: Linux 4.15.0-50-generic x86_64 x86_64

Installed compiler toolchains
-----------------------------
    native gcc: gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
    arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
    avr-gcc: missing
    mips-mti-elf-gcc: missing
    msp430-gcc: missing
    riscv-none-embed-gcc: missing
    xtensa-esp32-elf-gcc: missing
    xtensa-lx106-elf-gcc: missing
    clang: missing

Installed compiler libs
-----------------------
    arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
    riscv-none-embed-newlib: missing
    xtensa-esp32-elf-newlib: missing
    xtensa-lx106-elf-newlib: missing
    avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: missing
               cppcheck: missing
                doxygen: missing
                 flake8: missing
                    git: git version 2.17.1
                   make: GNU Make 4.1
                openocd: missing
                 python: Python 2.7.15rc1
                python2: Python 2.7.15rc1
                python3: Python 3.6.7
             coccinelle: missing

**Comment by olegart** [comment]
Fixed with https://github.com/unwireddevices/RIOT/commit/47c7aa0d022669f5b61535a4ed6b434b44c17593
