### ISSUE TITLE
Errors during compile for STM32f0

### ISSUE THREAD

**Issue by tatyanavolkova** [unwireddevices/RIOT#5]
For some reason, this fork of RIOT gives me errors when I try to compile the "hello-world" for STM32F0Discovery board, due to some missing constants. However, the original version of RIOT (from main repo) gives no such errors.

The log:

volkova_ta@volkova-ubuntu:~/git/RIOT/examples/hello-world$ BOARD=stm32f0discovery make
Building application "hello-world" for "stm32f0discovery" with MCU "stm32f0".

"make" -C /home/volkova_ta/git/RIOT/boards/stm32f0discovery
"make" -C /home/volkova_ta/git/RIOT/core
"make" -C /home/volkova_ta/git/RIOT/cpu/stm32f0
"make" -C /home/volkova_ta/git/RIOT/cpu/cortexm_common
"make" -C /home/volkova_ta/git/RIOT/cpu/cortexm_common/periph
"make" -C /home/volkova_ta/git/RIOT/cpu/stm32_common
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c: In function 'periph_apb_clk':
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:55:18: error: 'RCC_CFGR_PPRE1_DIV1' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE_DIV1'?
             case RCC_CFGR_PPRE1_DIV1:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE_DIV1
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:55:18: note: each undeclared identifier is reported only once for each function it appears in
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:58:18: error: 'RCC_CFGR_PPRE1_DIV2' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE1_DIV1'?
             case RCC_CFGR_PPRE1_DIV2:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE1_DIV1
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:61:18: error: 'RCC_CFGR_PPRE1_DIV4' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE1_DIV2'?
             case RCC_CFGR_PPRE1_DIV4:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE1_DIV2
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:64:18: error: 'RCC_CFGR_PPRE1_DIV8' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE1_DIV4'?
             case RCC_CFGR_PPRE1_DIV8:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE1_DIV4
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:67:18: error: 'RCC_CFGR_PPRE1_DIV16' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE1_DIV1'?
             case RCC_CFGR_PPRE1_DIV16:
                  ^~~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE1_DIV1
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:74:17: error: 'CLOCK_APB2_DIV' undeclared (first use in this function); did you mean 'CLOCK_APB1_DIV'?
         switch (CLOCK_APB2_DIV) {
                 ^~~~~~~~~~~~~~
                 CLOCK_APB1_DIV
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:75:18: error: 'RCC_CFGR_PPRE2_DIV1' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE1_DIV1'?
             case RCC_CFGR_PPRE2_DIV1:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE1_DIV1
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:78:18: error: 'RCC_CFGR_PPRE2_DIV2' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE2_DIV1'?
             case RCC_CFGR_PPRE2_DIV2:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE2_DIV1
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:81:18: error: 'RCC_CFGR_PPRE2_DIV4' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE2_DIV2'?
             case RCC_CFGR_PPRE2_DIV4:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE2_DIV2
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:84:18: error: 'RCC_CFGR_PPRE2_DIV8' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE2_DIV4'?
             case RCC_CFGR_PPRE2_DIV8:
                  ^~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE2_DIV4
/home/volkova_ta/git/RIOT/cpu/stm32_common/cpu_common.c:87:18: error: 'RCC_CFGR_PPRE2_DIV16' undeclared (first use in this function); did you mean 'RCC_CFGR_PPRE2_DIV1'?
             case RCC_CFGR_PPRE2_DIV16:
                  ^~~~~~~~~~~~~~~~~~~~
                  RCC_CFGR_PPRE2_DIV1
/home/volkova_ta/git/RIOT/Makefile.base:81: recipe for target '/home/volkova_ta/git/RIOT/examples/hello-world/bin/stm32f0discovery/stm32_common/cpu_common.o' failed
make[3]: *** [/home/volkova_ta/git/RIOT/examples/hello-world/bin/stm32f0discovery/stm32_common/cpu_common.o] Error 1
/home/volkova_ta/git/RIOT/Makefile.base:20: recipe for target 'ALL--/home/volkova_ta/git/RIOT/cpu/stm32_common' failed
make[2]: *** [ALL--/home/volkova_ta/git/RIOT/cpu/stm32_common] Error 2
/home/volkova_ta/git/RIOT/Makefile.base:20: recipe for target 'ALL--/home/volkova_ta/git/RIOT/cpu/stm32f0' failed
make[1]: *** [ALL--/home/volkova_ta/git/RIOT/cpu/stm32f0] Error 2
/home/volkova_ta/git/RIOT/examples/hello-world/../../Makefile.include:320: recipe for target 'link' failed
make: *** [link] Error 2

**Comment by olegart** [comment]
What branch was that?

loralan-public with the most recent changes builds with no problem.
